### ISSUE TITLE
Roster() can return nil

### ISSUE THREAD

**Issue by jeffallen** [dedis/onet#524]
The conode on dedis.ch crashed because of:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8088f6]

goroutine 531904 [running]:
go.dedis.ch/onet/v3.(*Roster).ServicePublics(0x0, 0xb14ad6, 0x7, 0xb14ad6, 0x7, 
0x115)
        /home/conode3/go/pkg/mod/go.dedis.ch/onet/v3@v3.0.0-pre3/tree.go:481 +0x
26
go.dedis.ch/onet/v3.(*TreeNodeInstance).Publics(0xc0001ee000, 0x10c, 0x10c, 0x1)
        /home/conode3/go/pkg/mod/go.dedis.ch/onet/v3@v3.0.0-pre3/treenode.go:655
 +0x89
go.dedis.ch/cothority/v3/blscosi/protocol.(*SubBlsCosi).makeResponse(0xc00039ce6
0, 0xc0000e7cb8, 0xc0001a85a0, 0x115)
        /home/conode3/cothority/blscosi/protocol/sub_protocol.go:358 +0x43
go.dedis.ch/cothority/v3/blscosi/protocol.(*SubBlsCosi).dispatchSubLeader(0xc000
39ce60, 0xc00024cb40, 0xc0001ee001)
        /home/conode3/cothority/blscosi/protocol/sub_protocol.go:247 +0x279
go.dedis.ch/cothority/v3/blscosi/protocol.(*SubBlsCosi).Dispatch(0xc00039ce60, 0
x0, 0x0)
        /home/conode3/cothority/blscosi/protocol/sub_protocol.go:103 +0xa5
```

**Comment by Gilthoniel** [comment]
I made a draft in [this branch](https://github.com/dedis/onet/tree/overlay_cache_524) to show you can remove the tree node and the roster cache. You can also clean the trees as we have a callback when protocol instances are done.

Unfortunately you only know when the current node is done which brings to an issue where the children can ask for the tree but the root has cleaned it up because the root was done.

**Comment by Gilthoniel** [comment]
Note that the draft is backward incompatible but that can be done in a backward compatible way
